### ISSUE TITLE
Select Engine and Space in the editor

### ISSUE THREAD

**Issue by playmer** [playmer/YTE#33]
We want the Engine and the currently viewed Space to be selectable in the editor so that we can add/remove components and change their properties.

In addition, currently all the components we can add are determined by the ComponentFactories, we should change this instead to walking our reflection and using Attributes to filter between Engine/Space/Normal components.

**Comment by JonathanAckerman** [comment]
Selecting the Space in the editor has a bug currently. It adds a copy of the entire space as a new composition. 

I think its just a visual bug since the copy doesn't show after reloading a level saved in this state. However on large levels (ie: presentationLevel aka the game), the editor freezes up for a long time.

**Comment by playmer** [comment]
I'll need to check, but this should be vastly improved in the current feature branch I'm working on. That being said I believe it still does create a new tree. If you want to file a new issue for fixing that, it's totally good. My plan is that in the future the space will simply be at the top level of the tree and there will be no space select button. (though maybe it will still exist to select it in the tree.)

**Comment by playmer** [comment]
To expand further. I fixed a bug when loading objects into the tree where each time an individual item was added, it would be selected, thus hitting the reflection system/creating the component properties in the component tree.
